# -*- coding: utf-8 -*-
"""test-jobRotation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EIgMbfUfPoiF5iEX2N1Ql5Nho6op4icj

# **Teste - Job Rotation**

**-> Pergunta 2**
"""

var1 = int(input())
x, y = 0, 1

while x < var1:
  x, y = y, x + y

print(x == var1)

"""**-> Pergunta 3**"""

import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""Importando os dados"""

with open('dados.json', encoding='utf-8') as my_json:
  dados = json.load(my_json)

"""Criando um DataFrame com Pandas"""

tabela = pd.DataFrame(dados)
tabela

"""Excluindo valores zerados"""

tabela_nova = tabela[tabela['valor'] < 1].index

tabela.drop(tabela_nova, inplace=True)
tabela

"""Menor valor de faturamento ocorrido em um dia do mês"""

tabela['valor'].min()

"""Maior valor de faturamento ocorrido em um dia do mês"""

tabela['valor'].max()

"""Número de dias no mês em que o valor de faturamento diário foi superior à média mensal"""

# Localizando a média mensal
media = tabela['valor'].mean()
media

fat_superior = tabela[tabela['valor'] > media]
fat_superior['valor'].count()
# 10 dias é o número em que o faturamento foi acima da média do mês

"""**-> Pergunta 4**"""

# Criando o DataFrame

info = [['SP', 67.836],
      ['RJ', 36.678],
      ['MG', 29.229],
      ['ES', 27.165],
      ['Outros', 19.849]]
    
df = pd.DataFrame(info, columns=['Estado', 'Fat. Mensal (R$)'])
df

# Percentual de representação que cada estado

df['Fat. Mensal (R$)'] / df['Fat. Mensal (R$)'].sum() * 100

"""-> Pergunta 5"""

nome = input('Digite alguma palavra: ')
print('Palavra invertida: ', nome[::-1])